import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "@/_context/providers";
import { Box, VStack } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box
            bgGradient="linear(to-r, rgba(173, 216, 230, 0.2), rgba(144, 238, 144, 0.2), rgba(109, 182, 225, 0.2))"
            height={"100vh"}
          >
            <VStack mx={"auto"} width={"100%"}>
              {children}
            </VStack>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
